/************************************************************************************
 * boards/st/nucleo-h753zi/nuttx-config/include/board.h
 ************************************************************************************/
#pragma once

#include "board_dma_map.h"

#include <nuttx/config.h>
#ifndef __ASSEMBLY__
# include <stdint.h>
#endif

#include "stm32_rcc.h"
#include "stm32_sdmmc.h"

/* Clocking *************************************************************************/
/* HSE = 8 MHz from ST-LINK MCO output */

#define STM32_BOARD_XTAL        8000000ul
#define STM32_HSI_FREQUENCY     16000000ul
#define STM32_LSI_FREQUENCY     32000
#define STM32_HSE_FREQUENCY     STM32_BOARD_XTAL
#define STM32_LSE_FREQUENCY     32768

/* PLL1: 8 MHz HSE / 2 * 200 / 2 = 400 MHz SYSCLK
 *   VCO = (8 / 2) * 200 = 800 MHz
 *   P   = 800 / 2       = 400 MHz  -> SYSCLK
 *   Q   = 800 / 4       = 200 MHz
 *   R   = 800 / 8       = 100 MHz
 */
#define STM32_BOARD_USEHSE
#define STM32_PLLCFG_PLLSRC     RCC_PLLCKSELR_PLLSRC_HSE

#define STM32_PLLCFG_PLL1CFG   (RCC_PLLCFGR_PLL1VCOSEL_WIDE | \
				RCC_PLLCFGR_PLL1RGE_4_8_MHZ | \
				RCC_PLLCFGR_DIVP1EN | \
				RCC_PLLCFGR_DIVQ1EN | \
				RCC_PLLCFGR_DIVR1EN)
#define STM32_PLLCFG_PLL1M      RCC_PLLCKSELR_DIVM1(2)
#define STM32_PLLCFG_PLL1N      RCC_PLL1DIVR_N1(200)
#define STM32_PLLCFG_PLL1P      RCC_PLL1DIVR_P1(2)
#define STM32_PLLCFG_PLL1Q      RCC_PLL1DIVR_Q1(4)
#define STM32_PLLCFG_PLL1R      RCC_PLL1DIVR_R1(8)

#define STM32_VCO1_FREQUENCY    ((STM32_HSE_FREQUENCY / 2) * 200)
#define STM32_PLL1P_FREQUENCY   (STM32_VCO1_FREQUENCY / 2)
#define STM32_PLL1Q_FREQUENCY   (STM32_VCO1_FREQUENCY / 4)
#define STM32_PLL1R_FREQUENCY   (STM32_VCO1_FREQUENCY / 8)

/* PLL2: for peripherals */
#define STM32_PLLCFG_PLL2CFG   (RCC_PLLCFGR_PLL2VCOSEL_WIDE | \
				RCC_PLLCFGR_PLL2RGE_4_8_MHZ | \
				RCC_PLLCFGR_DIVP2EN | \
				RCC_PLLCFGR_DIVQ2EN | \
				RCC_PLLCFGR_DIVR2EN)
#define STM32_PLLCFG_PLL2M      RCC_PLLCKSELR_DIVM2(2)
#define STM32_PLLCFG_PLL2N      RCC_PLL2DIVR_N2(48)
#define STM32_PLLCFG_PLL2P      RCC_PLL2DIVR_P2(2)
#define STM32_PLLCFG_PLL2Q      RCC_PLL2DIVR_Q2(2)
#define STM32_PLLCFG_PLL2R      RCC_PLL2DIVR_R2(2)

#define STM32_VCO2_FREQUENCY    ((STM32_HSE_FREQUENCY / 2) * 48)
#define STM32_PLL2P_FREQUENCY   (STM32_VCO2_FREQUENCY / 2)
#define STM32_PLL2Q_FREQUENCY   (STM32_VCO2_FREQUENCY / 2)
#define STM32_PLL2R_FREQUENCY   (STM32_VCO2_FREQUENCY / 2)

/* PLL3: for USB (48 MHz on Q) */
#define STM32_PLLCFG_PLL3CFG   (RCC_PLLCFGR_PLL3VCOSEL_WIDE | \
				RCC_PLLCFGR_PLL3RGE_4_8_MHZ | \
				RCC_PLLCFGR_DIVQ3EN)
#define STM32_PLLCFG_PLL3M      RCC_PLLCKSELR_DIVM3(2)
#define STM32_PLLCFG_PLL3N      RCC_PLL3DIVR_N3(48)
#define STM32_PLLCFG_PLL3P      RCC_PLL3DIVR_P3(2)
#define STM32_PLLCFG_PLL3Q      RCC_PLL3DIVR_Q3(4)
#define STM32_PLLCFG_PLL3R      RCC_PLL3DIVR_R3(2)

#define STM32_VCO3_FREQUENCY    ((STM32_HSE_FREQUENCY / 2) * 48)
#define STM32_PLL3P_FREQUENCY   (STM32_VCO3_FREQUENCY / 2)
#define STM32_PLL3Q_FREQUENCY   (STM32_VCO3_FREQUENCY / 4)
#define STM32_PLL3R_FREQUENCY   (STM32_VCO3_FREQUENCY / 2)

/* SYSCLK = PLL1P = 400 MHz; CPUCLK = SYSCLK / 1 = 400 MHz */
#define STM32_RCC_D1CFGR_D1CPRE  (RCC_D1CFGR_D1CPRE_SYSCLK)
#define STM32_SYSCLK_FREQUENCY    (STM32_PLL1P_FREQUENCY)
#define STM32_CPUCLK_FREQUENCY    (STM32_SYSCLK_FREQUENCY / 1)

/* HCLK = CPUCLK / 2 = 200 MHz */
#define STM32_RCC_D1CFGR_HPRE    RCC_D1CFGR_HPRE_SYSCLKd2
#define STM32_ACLK_FREQUENCY      (STM32_CPUCLK_FREQUENCY / 2)
#define STM32_HCLK_FREQUENCY      (STM32_CPUCLK_FREQUENCY / 2)
#define STM32_BOARD_HCLK          STM32_HCLK_FREQUENCY

/* PCLK1 = HCLK/2 = 100 MHz */
#define STM32_RCC_D2CFGR_D2PPRE1  RCC_D2CFGR_D2PPRE1_HCLKd2
#define STM32_PCLK1_FREQUENCY      (STM32_HCLK_FREQUENCY / 2)

/* PCLK2 = HCLK/2 = 100 MHz */
#define STM32_RCC_D2CFGR_D2PPRE2  RCC_D2CFGR_D2PPRE2_HCLKd2
#define STM32_PCLK2_FREQUENCY      (STM32_HCLK_FREQUENCY / 2)

/* PCLK3 = HCLK/2 = 100 MHz */
#define STM32_RCC_D1CFGR_D1PPRE   RCC_D1CFGR_D1PPRE_HCLKd2
#define STM32_PCLK3_FREQUENCY      (STM32_HCLK_FREQUENCY / 2)

/* PCLK4 = HCLK/2 = 100 MHz */
#define STM32_RCC_D3CFGR_D3PPRE   RCC_D3CFGR_D3PPRE_HCLKd2
#define STM32_PCLK4_FREQUENCY      (STM32_HCLK_FREQUENCY / 2)

/* Timer clocks */
#define STM32_APB1_TIM2_CLKIN    (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM3_CLKIN    (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM4_CLKIN    (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM5_CLKIN    (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM6_CLKIN    (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM7_CLKIN    (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM12_CLKIN   (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM13_CLKIN   (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM14_CLKIN   (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB2_TIM1_CLKIN    (2 * STM32_PCLK2_FREQUENCY)
#define STM32_APB2_TIM8_CLKIN    (2 * STM32_PCLK2_FREQUENCY)
#define STM32_APB2_TIM15_CLKIN   (2 * STM32_PCLK2_FREQUENCY)
#define STM32_APB2_TIM16_CLKIN   (2 * STM32_PCLK2_FREQUENCY)
#define STM32_APB2_TIM17_CLKIN   (2 * STM32_PCLK2_FREQUENCY)

/* Peripheral kernel clocks */
#define STM32_RCC_D2CCIP2R_I2C123SRC  RCC_D2CCIP2R_I2C123SEL_HSI
#define STM32_RCC_D3CCIPR_I2C4SRC     RCC_D3CCIPR_I2C4SEL_HSI
#define STM32_RCC_D2CCIP1R_SPI123SRC  RCC_D2CCIP1R_SPI123SEL_PLL2
#define STM32_RCC_D2CCIP1R_SPI45SRC   RCC_D2CCIP1R_SPI45SEL_PLL2
#define STM32_RCC_D3CCIPR_SPI6SRC     RCC_D3CCIPR_SPI6SEL_PLL2
#define STM32_RCC_D2CCIP2R_USBSRC     RCC_D2CCIP2R_USBSEL_PLL3
#define STM32_RCC_D3CCIPR_ADCSRC      RCC_D3CCIPR_ADCSEL_PLL2
#define STM32_RCC_D2CCIP1R_FDCANSEL   RCC_D2CCIP1R_FDCANSEL_HSE
#define STM32_FDCANCLK                 STM32_HSE_FREQUENCY

/* FLASH wait states: 4 is safe at ACLK=200 MHz */
#define BOARD_FLASH_WAITSTATES  4

/* SDMMC (not used, but macros required by NuttX headers) */
#define STM32_SDMMC_INIT_CLKDIV      (300 << STM32_SDMMC_CLKCR_CLKDIV_SHIFT)
#define STM32_SDMMC_MMCXFR_CLKDIV   (100 << STM32_SDMMC_CLKCR_CLKDIV_SHIFT)
#define STM32_SDMMC_SDXFR_CLKDIV    (100 << STM32_SDMMC_CLKCR_CLKDIV_SHIFT)
#define STM32_SDMMC_CLKCR_EDGE      STM32_SDMMC_CLKCR_NEGEDGE

/* LED index values must match PX4's drv_board_led.h constants:
 *   LED_BLUE  = 0
 *   LED_RED   = 1  (also LED_AMBER)
 *   (index 2 unused)
 *   LED_GREEN = 3
 */
#define BOARD_LED1      0   /* LD2 Blue  PE1  -- LED_BLUE=0  */
#define BOARD_LED2      1   /* LD3 Red   PB14 -- LED_RED=1   */
#define BOARD_LED3      3   /* LD1 Green PB0  -- LED_GREEN=3 */
#define BOARD_NLEDS     4   /* array size (highest index + 1) */

#define BOARD_LED_BLUE   BOARD_LED1
#define BOARD_LED_RED    BOARD_LED2
#define BOARD_LED_GREEN  BOARD_LED3

/* NuttX arch LED event codes */
#define LED_STARTED      0
#define LED_HEAPALLOCATE 1
#define LED_IRQSENABLED  2
#define LED_STACKCREATED 3
#define LED_INIRQ        4
#define LED_SIGNAL       5
#define LED_ASSERTION    6
#define LED_PANIC        7
#define LED_IDLE         8

/* UART pin alternate functions */
#define GPIO_USART3_RX  GPIO_USART3_RX_3   /* PD9  -- ST-LINK virtual COM */
#define GPIO_USART3_TX  GPIO_USART3_TX_3   /* PD8  */

#define GPIO_USART6_RX  GPIO_USART6_RX_2   /* PG9  */
#define GPIO_USART6_TX  GPIO_USART6_TX_2   /* PG14 */

/* SPI3 (Arduino shield) */
#define GPIO_SPI3_MISO  GPIO_SPI3_MISO_1   /* PB4 */
#define GPIO_SPI3_MOSI  GPIO_SPI3_MOSI_2   /* PB5 */
#define GPIO_SPI3_SCK   GPIO_SPI3_SCK_1    /* PB3 */

/* I2C1 */
#define GPIO_I2C1_SCL   GPIO_I2C1_SCL_2    /* PB8 */
#define GPIO_I2C1_SDA   GPIO_I2C1_SDA_2    /* PB9 */

/* Probe/timing stubs (required by px4 arch headers) */
#define PROBE_INIT(mask)
#define PROBE(n,s)
#define PROBE_MARK(n)
